name: Deploy Preview on Netlify

on:
  push:
    branches:
      - deploy
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1     
      - name: Deploy netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }} 
        run: |
          npx netlify-cli deploy --dir=_site --prod
        
